# -- Site Configuration --
# Refer to the theme docs for more details about each of these parameters.
# https://jpanther.github.io/congo/docs/getting-started/

baseURL = "https://wafwa01.github.io/blog/"
defaultContentLanguage = "en"

enableRobotsTXT = true
summaryLength = 0
rssLimit = 20

[outputs]
  home = ["HTML", "RSS", "JSON"]
